ratings:
  - target: fitness
    values:
      - id: 1
        min: 0
        max: 5
        description: Es besteht akuter Handlungsbedarf, da in einem Fehlerfall nicht das Problem behoben werden kann, sondern erst aufwendige Vorarbeiten erledigt werden müssen. Das System ist akut gefährdet.
      - id: 2
        min: 6
        max: 11
        description: Es besteht Handlungsbedarf, um im Fehlerfall vorbereitet zu sein.
      - id: 3
        min: 12
        max: 12
        description: Es ist alles ok. Sie sind mit Ihrer Software super aufgestellt.