targets:
  1:
    label: freeride
  2:
    label: freestyle
  3:
    label: freestyle-wave
  4:
    label: wave

questions:
  1:
    text: Welches sind die Hauptbedingungen, unter denen du surfst?
    type: multi
    options:
      1:
        text: Flachwasser
        scores: 
          1:
            value: 3
            why: Auf dem Meer kannst Du lange Schläge fahren
          2:
            score: 2
            why: Freestylen im Flachwasser ist genau Dein Ding
          3: 
            score: 1
            why: Funktioniert super im Flachwasser, scheut aber auch die Welle nicht
          4:
            score: 0
            why: Ein Wave-Board ist im Flachwasser nicht die erste Wahl
      2:
        text: Kleine Welle (bis Kofphoch, eher Ost- und Nordsee)
        scores:
          1:
            value: 0
          2:
            value: 1
          3:
            value: 3
          4:
            value: 2
      4:
        text: Große Klopfer
        scores:
          1: 
            value: 0
          2:
            value: 0
          3: 
            value: 1
          4:
            value: 3
            why: In großen Klopfern geht nichts über ein echtes Wave-Board
  2:
    text: Dein Hauptrevier ist Flachwasser. Gehst du trotzdem hin und wieder in die Welle?
    type: binary
    dependencies: or
      - 1:1
    options:
      1:
        text: ja
        scores: 
          3: 
            value: 3
            why: Freestyle Wave ist eine gute Kombination, wenn du Flachwasser und Welle magst
          4: 
            value: 1  
            why: Ein Wave-Board ist besser als eine reine Flachwasserrakete, aber nicht optimal. 
      2:
        text: nein
  3:
    text: Wieviele Tage surfst du im Jahr?
    type: single
    options:
      1:
        text: Weniger als 20
        scores:
          1: 
      2:
        text: Zwischen 20 und 40
      4:
        text: Mehr als 40
        scores:
          4:
  4:
    text: Wann bist du geboren?
    type: single
    options:
      1:
        text: Vor 1960
      2:
        text: Zwischen 1960 und 1980
      4:
        text: Zwischen 1980 und 2000
      8:
        text: Nach 2000
  5:
    text: Wieviel wiegst du?
    type: single
    options:
      1:
        text: Unter 60 KG
      2:
        text: Zwischen 60 und 70 KG
      4:
        text: Zwischen 70 und 85 KG
      8:
        text: Zwischen 85 und 100 KG
      16:
        text: Über 100 KG